### ISSUE TITLE
how to apply this pretrained model on new data

### ISSUE THREAD

**Issue by chiseo36** [omarmohamed15/SCALODEEP#1]
Dear Omar, i have the new data sets and I want to apply the scalodeep pretrained model on my data.Then how can i generate the Scalograms from my data.Can you please suggest.Thanks.

**Comment by omarmohamed15** [comment]
Dear Chiseo, we will update the repository to include predictions on new data. Please, keep tuned.

**Comment by omarmohamed15** [comment]
@chiseo36 The code has been updated.

Best,
Omar

**Comment by chiseo36** [comment]
Dear sir, I want to train the network with my collected local data sets along with the north California data set.can you please let me know how to conduct this.The code for the training and validation of scalodeep is not updated.Thanks and waiting for your response.
